homeassistant:
  name: Dev Home
  latitude: 51.509865
  longitude: -0.118092
  elevation: 20
  unit_system: metric
  time_zone: Europe/London
  country: GB
  currency: GBP
  allowlist_external_dirs:
    - "/workspaces/homeassistant/config"

default_config:

# Load custom components from mounted folder
custom_components:

frontend:

logger:
  default: info

